#Server
server:
  port: 8083
  servlet:
    context-path: /
#thymeleaf 模版
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
  # 电子邮箱配置
  mail:
    protocol: smtp #smtp是邮件发送协议，pop3和imap是邮件接收协议。因为我们要发送邮件，因此是smtp
    host: smtp.126.com #邮件发送服务器的主机，这里采用的是126邮箱来发送邮件
    port: 25 #邮件发送服务器的端口
    username: yang2008cs@126.com #邮件发送服务器的用户名
    password: ****** #密码
    properties:
          mail:
            smtp:
              auth: true #一般情况下，发送邮件都是要进行验证
              starttls:
                enable: true
                required: true

#MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/bill?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 123456
  #Redis配置
  redis:
    host: localhost
    password: 123456
    port: 6379

#Mybatis日志
mybatis:
  type-aliases-package: com.bill.entity
  mapperLocations: classpath:mapper/**/*.xml

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true

#日志配置
logging:
  file: ./logs/bill.log
  level:
    com.len.mapper: debug


bill:
   # 系统标识
  identification: bill

  uploadPath: ./file/
  isDayType: false

  imagePath: ./image/
  #盐
  salt: _bill


